---
- name: Update Netbird on endpoints
  hosts: api
  become: yes
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade only netbird package
      apt:
        name: netbird
        state: latest
