---
- name: Update Netbird on endpoints
  hosts: api
  become: yes
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade only netbird package
      apt:
        name: netbird
        state: latest

    - name: Restart Netbird service (optional)
      systemd:
        name: netbird
        state: restarted
        enabled: yes
